PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY,
    join_code TEXT NOT NULL,
    admin_cookie TEXT NOT NULL,
    quiz_id TEXT NOT NULL,
    created_at TEXT NOT NULL,

    question_1 INTEGER DEFAULT 0,
    question_2 INTEGER DEFAULT 0,
    question_3 INTEGER DEFAULT 0,
    question_4 INTEGER DEFAULT 0,
    question_5 INTEGER DEFAULT 0,
    question_6 INTEGER DEFAULT 0,
    question_7 INTEGER DEFAULT 0,
    question_8 INTEGER DEFAULT 0,
    question_9 INTEGER DEFAULT 0,
    question_10 INTEGER DEFAULT 0,
    question_11 INTEGER DEFAULT 0,
    question_12 INTEGER DEFAULT 0,
    question_13 INTEGER DEFAULT 0,
    question_14 INTEGER DEFAULT 0,
    question_15 INTEGER DEFAULT 0,
    question_16 INTEGER DEFAULT 0,
    question_17 INTEGER DEFAULT 0,
    question_18 INTEGER DEFAULT 0,
    question_19 INTEGER DEFAULT 0,
    question_20 INTEGER DEFAULT 0,
    question_21 INTEGER DEFAULT 0,
    question_22 INTEGER DEFAULT 0,
    question_23 INTEGER DEFAULT 0,
    question_24 INTEGER DEFAULT 0,
    question_25 INTEGER DEFAULT 0,
    question_26 INTEGER DEFAULT 0,
    question_27 INTEGER DEFAULT 0,
    question_28 INTEGER DEFAULT 0,
    question_29 INTEGER DEFAULT 0,
    question_30 INTEGER DEFAULT 0,
    question_31 INTEGER DEFAULT 0,
    question_32 INTEGER DEFAULT 0,
    question_33 INTEGER DEFAULT 0,
    question_34 INTEGER DEFAULT 0,
    question_35 INTEGER DEFAULT 0,
    question_36 INTEGER DEFAULT 0,
    question_37 INTEGER DEFAULT 0,
    question_38 INTEGER DEFAULT 0,
    question_39 INTEGER DEFAULT 0,
    question_40 INTEGER DEFAULT 0,
    question_41 INTEGER DEFAULT 0,
    question_42 INTEGER DEFAULT 0,
    question_43 INTEGER DEFAULT 0,
    question_44 INTEGER DEFAULT 0,
    question_45 INTEGER DEFAULT 0,
    question_46 INTEGER DEFAULT 0,
    question_47 INTEGER DEFAULT 0,
    question_48 INTEGER DEFAULT 0,
    question_49 INTEGER DEFAULT 0,
    question_50 INTEGER DEFAULT 0

);


CREATE TABLE IF NOT EXISTS game (
    user_cookie TEXT NOT NULL,
    session_id TEXT NOT NULL,

    answer_1 INTEGER,
    answer_2 INTEGER,
    answer_3 INTEGER,
    answer_4 INTEGER,
    answer_5 INTEGER,
    answer_6 INTEGER,
    answer_7 INTEGER,
    answer_8 INTEGER,
    answer_9 INTEGER,
    answer_10 INTEGER,
    answer_11 INTEGER,
    answer_12 INTEGER,
    answer_13 INTEGER,
    answer_14 INTEGER,
    answer_15 INTEGER,
    answer_16 INTEGER,
    answer_17 INTEGER,
    answer_18 INTEGER,
    answer_19 INTEGER,
    answer_20 INTEGER,
    answer_21 INTEGER,
    answer_22 INTEGER,
    answer_23 INTEGER,
    answer_24 INTEGER,
    answer_25 INTEGER,
    answer_26 INTEGER,
    answer_27 INTEGER,
    answer_28 INTEGER,
    answer_29 INTEGER,
    answer_30 INTEGER,
    answer_31 INTEGER,
    answer_32 INTEGER,
    answer_33 INTEGER,
    answer_34 INTEGER,
    answer_35 INTEGER,
    answer_36 INTEGER,
    answer_37 INTEGER,
    answer_38 INTEGER,
    answer_39 INTEGER,
    answer_40 INTEGER,
    answer_41 INTEGER,
    answer_42 INTEGER,
    answer_43 INTEGER,
    answer_44 INTEGER,
    answer_45 INTEGER,
    answer_46 INTEGER,
    answer_47 INTEGER,
    answer_48 INTEGER,
    answer_49 INTEGER,
    answer_50 INTEGER,

    FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE
);


CREATE UNIQUE INDEX IF NOT EXISTS idx_sessions_admin_cookie ON sessions(admin_cookie);
CREATE UNIQUE INDEX IF NOT EXISTS idx_game_session_user ON game(session_id, user_cookie);

CREATE INDEX IF NOT EXISTS idx_game_session ON game(session_id);
CREATE INDEX IF NOT EXISTS idx_game_user_cookie ON game(user_cookie);
CREATE INDEX IF NOT EXISTS idx_sessions_created_at ON sessions(created_at);
